### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-standalone#6]
Currently pyblish-standalone will start a new python process, when executed.

Having a process already running would increase the startup. This could happen either manually by the user setup, with initializing the process when launching the host, or not terminate the process when exiting so subsequent publish tries will happen faster.

**Comment by mottosso** [comment]
Did you try and launch a separate process independently, say on OS startup? The standalone process should pick this up automatically, and re-use it, like hosts do.

This should suffice.

**preload_qml.bat**

``` python
import pyblish_integration

# Pre-load QML and start a dummy-server
# so that it won't go to sleep.
pyblish_integration.setup()
```

**Comment by tokejepsen** [comment]
ahh, this might work. Will investigate, where to put this in the pipeline.

**Comment by mottosso** [comment]
You might have to keep this process alive, as you are in the executable. Otherwise the preload will remain, but the server will die. The preload will later die "of loneliness" unless it has a server to talk to.

This means you'll need to keep a console window open.. You could hide it, but that might cause other issues.

I'm working on putting QML in the tray. This would solve this issue, as it would act as a permanent, but hidden, server, that you could still access via the tray icon.
- https://github.com/pyblish/taskbar

**Comment by tokejepsen** [comment]
> I'm working on putting QML in the tray. This would solve this issue, as it would act as a permanent, but hidden, server, that you could still access via the tray icon.

Cool!
